export interface Sensor {
    id: number,
    reading_time:string,
    Device_Id:string,
    Client:string,
    Voltage_AN:string,
    Voltage_BN:string,
    Voltage_CN:string,
    Voltage_Avg:string,
    Frequency:string,
    Current_A:string,
    Current_B:string,
    Current_C:string,
    Current_Avg:string,
    Active_Power:string,
    Reactive_Power:string,
    Apparent_Power:string,
    Power_Factor:string,
    KWH:string,
    kVARh:string,
    kVAh:string,
    // new
    PF:string,
    KWh_DpR:string,
    KWh_D:string,
    KWh_DnR:string,
    KVARh_D:string,
    KVARh_R:string,
    KVARh_DpR:string,
    KVARh_DnR:string,
    KVAh_D:string,
    KVAh_DpR:string,
    KVAh_DnR:string,
    Aavg:string,
    V_LL:string,
    V_LN:string,
    KW:string,
    KVAR:string,
    KVA:string,


}